import React from 'react';
import Nav from './components/Nav'; // Import the Navbar component
import './globals.css';
import { Metadata } from 'next';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.7/dist/tailwind.min.css"
        />
      
      </head>
      <body className={inter.className}>
        <Nav initialActive={undefined} /> {/* Include the Navbar component */}
        {children}
      </body>
    </html>
  );
}
